<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Sales Report</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        
        body {
            font-family: 'Arial', sans-serif;
            color: #2c3e50;
            line-height: 1.6;
            padding: 40px;
        }
        
        .header {
            text-align: center;
            margin-bottom: 40px;
            padding-bottom: 20px;
            border-bottom: 3px solid #2c3e50;
        }
        
        .header h1 {
            font-size: 32px;
            color: #2c3e50;
            margin-bottom: 5px;
        }
        
        .header .subtitle {
            font-size: 14px;
            color: #7f8c8d;
        }
        
        .report-info {
            margin-bottom: 30px;
            background: #f8f9fa;
            padding: 15px;
            border-radius: 4px;
        }
        
        .report-info table {
            width: 100%;
        }
        
        .report-info td {
            padding: 5px 0;
            font-size: 13px;
        }
        
        .report-info td:first-child {
            font-weight: 600;
            width: 150px;
        }
        
        .summary-grid {
            display: table;
            width: 100%;
            margin-bottom: 30px;
        }
        
        .summary-card {
            display: table-cell;
            width: 25%;
            padding: 15px;
            text-align: center;
            background: #ecf0f1;
            border-right: 2px solid white;
        }
        
        .summary-card:last-child {
            border-right: none;
        }
        
        .summary-label {
            font-size: 11px;
            color: #7f8c8d;
            text-transform: uppercase;
            margin-bottom: 5px;
        }
        
        .summary-value {
            font-size: 20px;
            font-weight: 700;
            color: #2c3e50;
        }
        
        table.transactions {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        
        table.transactions thead {
            background: #2c3e50;
            color: white;
        }
        
        table.transactions th {
            padding: 12px 8px;
            text-align: left;
            font-size: 11px;
            text-transform: uppercase;
            letter-spacing: 0.5px;
        }
        
        table.transactions td {
            padding: 10px 8px;
            border-bottom: 1px solid #ecf0f1;
            font-size: 12px;
        }
        
        table.transactions tbody tr:nth-child(even) {
            background: #f8f9fa;
        }
        
        .badge {
            display: inline-block;
            padding: 3px 8px;
            border-radius: 3px;
            font-size: 10px;
            font-weight: 600;
        }
        
        .badge-cash {
            background: #d4edda;
            color: #155724;
        }
        
        .badge-card {
            background: #d1ecf1;
            color: #0c5460;
        }
        
        .footer {
            margin-top: 40px;
            padding-top: 20px;
            border-top: 2px solid #ecf0f1;
            text-align: center;
            font-size: 11px;
            color: #95a5a6;
        }
        
        .footer strong {
            color: #16a085;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>LAPOS</h1>
        <div class="subtitle">Sales Report</div>
    </div>
    
    <div class="report-info">
        <table>
            <tr>
                <td>Report Date:</td>
                <td>{{ date('d F Y, H:i') }}</td>
            </tr>
            <tr>
                <td>Period:</td>
                <td>{{ $summary['start_date'] }} - {{ $summary['end_date'] }}</td>
            </tr>
            <tr>
                <td>Generated By:</td>
                <td>LAPOS System</td>
            </tr>
        </table>
    </div>
    
    <div class="summary-grid">
        <div class="summary-card">
            <div class="summary-label">Transactions</div>
            <div class="summary-value">{{ $summary['total_transactions'] }}</div>
        </div>
        <div class="summary-card">
            <div class="summary-label">Total Revenue</div>
            <div class="summary-value">Rp {{ number_format($summary['total_revenue'], 0, ',', '.') }}</div>
        </div>
        <div class="summary-card">
            <div class="summary-label">Cash</div>
            <div class="summary-value">Rp {{ number_format($summary['total_cash'], 0, ',', '.') }}</div>
        </div>
        <div class="summary-card">
            <div class="summary-label">Card</div>
            <div class="summary-value">Rp {{ number_format($summary['total_card'], 0, ',', '.') }}</div>
        </div>
    </div>
    
    <h3 style="margin-bottom: 15px; color: #2c3e50;">Transaction Details</h3>
    
    <table class="transactions">
        <thead>
            <tr>
                <th>Code</th>
                <th>Date</th>
                <th>Time</th>
                <th>Items</th>
                <th>Payment</th>
                <th>Mode</th>
                <th style="text-align: right;">Total</th>
            </tr>
        </thead>
        <tbody>
            @foreach($transactions as $transaction)
            <tr>
                <td><strong>{{ $transaction->transaction_code }}</strong></td>
                <td>{{ $transaction->created_at->format('d M Y') }}</td>
                <td>{{ $transaction->created_at->format('H:i') }}</td>
                <td>{{ $transaction->details->count() }} items</td>
                <td>
                    <span class="badge {{ $transaction->payment_method == 'tunai' ? 'badge-cash' : 'badge-card' }}">
                        {{ ucfirst($transaction->payment_method) }}
                    </span>
                </td>
                <td>
                    <span style="font-size: 9px; padding: 2px 6px; background: {{ $transaction->currency_mode == 'redenominated' ? '#fff3cd' : '#e7f3ff' }}; border-radius: 3px;">
                        {{ $transaction->currency_mode == 'redenominated' ? 'Redom' : 'Std' }}
                    </span>
                </td>
                <td style="text-align: right;">
                    <strong>
                        @if($transaction->currency_mode == 'redenominated')
                            Rp {{ number_format($transaction->total / 1000, 2, ',', '.') }}
                        @else
                            Rp {{ number_format($transaction->total, 0, ',', '.') }}
                        @endif
                    </strong>
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>
    
    <div class="footer">
        <p>This is a computer-generated document. No signature is required.</p>
        <p style="margin-top: 10px;">Powered by <strong>e.bitzy.id</strong></p>
    </div>
</body>
</html>
